// src/modules/customer-portal/pages/SignatureEvidenceCard.jsx
import React from 'react'
import { Clock, Mail, User, FileText, CheckCircle2 } from 'lucide-react'

export default function SignatureEvidenceCard({ evidence, auditPdfUrl }) {
  if (!evidence) return null

  const {
    documentHash,
    timestamp,
    ip,
    device,
    otpRef,
    signerId,
    agentId,
    certificateChain,
    eidasLevel,
  } = evidence

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 space-y-4">
      <h2 className="text-sm font-semibold text-gray-900 flex items-center gap-2">
        <span className="inline-flex h-6 w-6 items-center justify-center rounded-full border border-green-300 bg-green-50 text-xs">
          ✓
        </span>
        <span>Signature Evidence</span>
      </h2>

      <div className="space-y-4 text-xs text-gray-700">
        {/* Document hash */}
        <div>
          <p className="font-semibold text-gray-800 mb-1">Document Hash</p>
          <p className="font-mono text-[11px] break-all text-gray-500">{documentHash}</p>
        </div>

        {/* Timestamp */}
        <div className="flex items-start gap-2">
          <Clock className="w-4 h-4 mt-0.5 text-gray-400" />
          <div>
            <p className="font-semibold text-gray-800">Timestamp</p>
            <p className="mt-1 text-gray-700">{timestamp}</p>
          </div>
        </div>

        {/* IP & Device */}
        <div className="flex items-start gap-2">
          <FileText className="w-4 h-4 mt-0.5 text-gray-400" />
          <div>
            <p className="font-semibold text-gray-800">IP Address &amp; Device</p>
            <p className="mt-1 text-gray-700">IP: {ip}</p>
            <p className="text-gray-500">{device}</p>
          </div>
        </div>

        {/* OTP Verification */}
        <div className="flex items-start gap-2">
          <Mail className="w-4 h-4 mt-0.5 text-gray-400" />
          <div>
            <p className="font-semibold text-gray-800">OTP Verification</p>
            <p className="mt-1 text-gray-700">{otpRef}</p>
          </div>
        </div>

        {/* Participant IDs */}
        <div className="flex items-start gap-2">
          <User className="w-4 h-4 mt-0.5 text-gray-400" />
          <div>
            <p className="font-semibold text-gray-800">Participant IDs</p>
            <p className="mt-1 text-gray-700">Signer: {signerId}</p>
            <p className="text-gray-700">Agent: {agentId}</p>
          </div>
        </div>

        {/* Certificate chain */}
        {certificateChain && certificateChain.length > 0 && (
          <div>
            <p className="font-semibold text-gray-800 mb-1">Certificate Chain</p>
            <ul className="space-y-1">
              {certificateChain.map((item, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="mt-[3px] inline-block h-2 w-2 rounded-full bg-green-500" />
                  <span className="text-gray-700">{item}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* eIDAS / compliance badge */}
        <div className="mt-4 rounded-xl border border-green-200 bg-green-50 px-3 py-3 flex items-start gap-2">
          <CheckCircle2 className="w-4 h-4 text-green-600 mt-0.5" />
          <div>
            <p className="text-xs font-semibold text-green-800">
              {eidasLevel || 'eIDAS Article 26 Compliant'}
            </p>
            <p className="text-[11px] text-green-700 mt-1">
              Advanced Electronic Signature (AES) – evidence generated by JenusSign.
            </p>
          </div>
        </div>

        {/* Link to audit trail PDF */}
        {auditPdfUrl && (
          <a
            href={auditPdfUrl}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1 text-xs text-primary-700 hover:text-primary-800 mt-2"
          >
            <FileText className="w-4 h-4" />
            <span>Open full audit trail PDF</span>
          </a>
        )}
      </div>
    </div>
  )
}
